Kap05/det
DHBW-FN/tutorium-linear-algebra pull request #21
Opened 2023-03-07 14:38 UTC by FelixSchladt

2023-03-07 14:51 UTC, mario4180 approved these changes

2023-03-07 15:14 UTC, TobiasGoetz requested changes
Ein paar Aenderungen bzgl sections.
Bitte darauf achten die makefile nicht zu committen.
Rest passt.

2023-03-07 15:14 UTC, TobiasGoetz commented on Tutorium05/sections/det.tex
> +\subsection{Determinante - Sätze}
```suggestion
\subsection{Sätze}
```

2023-03-07 22:59 UTC, mario4180 approved these changes

2023-03-08 09:36 UTC, TobiasGoetz approved these changes

2023-03-08 09:37 UTC, merged