Kap03/skalar
DHBW-FN/tutorium-linear-algebra pull request #9
Opened 2023-02-08 15:57 UTC by FelixSchladt

Bitte korrektur lesen

2023-02-08 23:26 UTC, mario4180 submitted a review, later dismissed

2023-02-08 23:28 UTC, TobiasGoetz requested changes
Hab mir einige Aufgaben angeschaut aber nicht nochmal alle durchgerechnet. Dafür hab ich jetzt keine Lust mehr.

- Prinzipiell gut. Paar Schreibfehler hier und da.
- Achte bitte darauf, dass das styling ordentlich ist (enumerate und itemize verwenden)
- Eventuell nächstes Mal Aufgaben nur Aufgaben, die ohne Taschenrechner machbar sind, geht ja nur darum das Prinzip zu verstehen.
- Du hast die main.pdf gepusht, hab ich wieder rausgenommen

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +		\item orthogonal Komplement von $\vec{a}$ in Richtung $\vec{e}$
```suggestion
		\item orthogonales Komplement von $\vec{a}$ in Richtung $\vec{e}$
```

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +	Lösung Orthogonale Projektion\\
Wiederholung der Ueberschrift?
```suggestion
```

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +	Übung Orthogonale Projektion \\
Wiederhung der Ueberschrift?
```suggestion
```

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +	$\vec{a} = \vec{a}_{\parallel} + \vec{a}_{\perp} = (1, 1, 1) + (1, -3, 2) = (2, -2, 3)$\\
Kurz vergessen wie Aufzählunge in Latex gemacht werden?
```suggestion

    \begin{enumerate}
        \item Bilden von $\vec{a}_{\parallel}$\\
        $\vec{a}_{\parallel} = \frac{1}{\sqrt{3}} \cdot <(2, -2, 3), (1, 1, 1)> \cdot \frac{1}{\sqrt{3}} \cdot (1, 1, 1)$
        $= \frac{1}{3} \cdot 3 \cdot (1, 1, 1,) = (1, 1, 1)$
        \item Bilden von $\vec{a}_{\perp}$\\
        $\vec{a}_{\perp} = \vec{a} - \vec{a}_{\parallel} = (2, -2, 3) - (1, 1, 1) = (1, -3 , 2)$
        \item Überprüfung\\
        $\vec{a} = \vec{a}_{\parallel} + \vec{a}_{\perp} = (1, 1, 1) + (1, -3, 2) = (2, -2, 3)$
    \end{enumerate}
```

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +	Orthogonale Zerlegung von $\vec{a}$ in Richtung von $\vec{b}$
Um im Stil konsistent zu bleiben Aufgaben als enumerate
```suggestion
    \begin{enumerate}
        \item Orthogonale Zerlegung von $\vec{a}$ in Richtung von $\vec{b}$
    \end{enumerate}
```

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +	$\frac{11}{13}(-2, 3) + \frac{8}{13}(6, 4) = (2, 5)$ \\
Enumerate benutzen
```suggestion
    \begin{enumerate}
        \item Bilden des Einheitsvektors \\
        $\vec{e} = \frac{\vec{b}}{\lvert \vec{b} \rvert} = \frac{1}{\sqrt{13}} \cdot (-2, 3)$\\
        \item Bilden von $\vec{a}_{\parallel}$
        $\vec{a}_{\parallel} = \frac{1}{\sqrt{13}} \cdot <(-2, 3), (2, 5)> \cdot \frac{1}{\sqrt{13}} \cdot (-2, 3)$ \\
        $= \frac{1}{13} \cdot 11 \cdot (-2, 3) = \frac{11}{13}(-2, 3)$\\
        \textit{Faktor von $\vec{e}$  aus Skalarprodukt ausgeklammert}\\
        \item Bilden von $\vec{a}_{\perp}$ \\
        $\vec{a}_{\perp} = \vec{a} - \vec{a}_{\parallel} = (2, 5) - \frac{11}{13} \cdot (-2, 3)$\\
        $= (\frac{48}{13}, \frac{32}{13}) = \frac{8}{13}(6, 4)$\\
        \item Überprüfung \\
        $\vec{a} = \vec{a}_{\parallel} + \vec{a}_{\perp}$\\
        $\frac{11}{13}(-2, 3) + \frac{8}{13}(6, 4) = (2, 5)$ \\
    \end{enumerate}
```

2023-02-08 23:28 UTC, TobiasGoetz commented on Tutorium03/sections/Skalarprodukt.tex
> +	$\varphi = \arccos(\frac{11}{\sqrt{53} \cdot \sqrt{34}}) = 75$°
Aufzählungen werden so gemacht
```suggestion
    \begin{enumerate}
        \item $\vec{a} = (2\pi, 7)$ $\vec{b} = (-3.5, \pi)$ \\
        Skalarprodukt von $\vec{a}$ und $\vec{b}$ \\
        $\vec{a} \bullet \vec{b} = 2\pi \cdot (-3.5) + 7 \cdot \pi = 7\pi - 7\pi = 0$ \\
        $\rightarrow$ Somit sind die Vektoren orthogonal und der Winkel ist 90° \\
        $ $ \\
        \item $\vec{a} = (-2, 7)$ $\vec{b} = (5, 3)$
        Skalarprodukt von $\vec{a}$ und $\vec{b}$ \\
        $\vec{a} \bullet \vec{b} = -2 \cdot 5 + 7 \cdot 3 = 11$ \\
        Betrag von $\vec{a}$ und $\vec{b}$ \\
        $\lVert \vec{a} \rVert = \sqrt{(-2)^2 + 7^2} = \sqrt{53}$ \\
        $\lVert \vec{b} \rVert = \sqrt{5^2 + 3^2} = \sqrt{34}$ \\
        Winkel zwischen $\vec{a}$ und $\vec{b}$ \\
        $\varphi = \arccos(\frac{11}{\sqrt{53} \cdot \sqrt{34}}) = 75$°
    \end{enumerate}
```

2023-02-09 09:47 UTC, TobiasGoetz approved these changes
Looks good to me!

2023-02-09 09:50 UTC, merged